### PR TITLE
Custom template 

### PR DESCRIPTION
**Pull request by ooraini**
You can create custom template (see program.cs in the example project)

there is a lot to be done. I am planing to do more.

hope you like it!

### CODE REVIEW

**Comment by doxakis** [comment]
Hi,

I like the way you can create the template.
Ex: .LinkStyle((link, text) => $"&lt;a href='{link}'&gt;{text}&lt;/a&gt;")
This is easier to read than : &lt;a href='{0}'&gt;{1}&lt;/a&gt;

I think we could make MailTemplateBuilder more flexible and do not force the user to define all properties.
By default, a simple template could be applied and you can override what you want.
Or, MailBodyTemplate could be refractored with a fluent interface instead.

The function ToBody() and ToBlock() of the class MailBlockFluent seems like a duplicate of ToString(). Maybe something like: GenerateHtml() can be more intuitive.

Thanks!

**Comment by ooraini** [comment]
In the MailTemplateBuilder  we either use the builder or not, if we don't client code could 
override one of the filed by calling a method twice for example 
`
.CreatTemplate()
.Head()
.Body()
.ParagraphStyle()
.Head()
`
by using the builder client code must call every method in the right order for the code to compile.
I removed some of the builder methods and provided a parameter-less version of each one which defaults to a very simple style for example LinkStyle() with no parameters will default to $"a href='{link}'>{text} /a"
take look at MailTemplateFactory I noticed that it's not possible to use lambdas with very long string
we are going to use string.format sometimes.

**Comment by doxakis** [comment]
Hi,
It looks great. But, I think it may be better to not strictly follow the builder design pattern.

I will work on a new branch. I have an idea how it could be done to define the custom template with a fluent interface. After that, we can compare and choose the good part.

**Comment by doxakis** [comment]
Hi,
I worked on the branch "refractor-template".
You will find similar part coming from your code.

Before:
```
template.Paragraph = "<p style='color: blue;'>{0}</p>";
```

After:
```
template.Paragraph(m => $"<p style='color: blue;'>{m.Content}</p>")
```
A more useful example:
```
template
    .Paragraph(m => $"<p style='color: blue;'>{m.Content}</p>")
    .Link(m => $"<a href='{m.Link}'>{m.Content}</a>")
    .Body(m => "<html><body>" + m.Content + "<br />" + m.Footer + "</body></html>");
```
What do you think about this implementation?

**Pull request closed without merging**
